### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by nick-bai** [hyperf-cloud/di#1]
https://github.com/hyperf-cloud/di/blob/21496582de2bcc41579e2e0267e31bd36cf1e0a3/src/Definition/DefinitionSource.php#L205

**Comment by huangzhhui** [comment]
哪里语法错误了呢？

**Comment by nick-bai** [comment]
[, $annotationMetadata, $aspectMetadata]  这里，解构出来的数组，第一个元素没有值

**Comment by nick-bai** [comment]
这难道是新语法吗？我ide设置成 php7.2 也是报错啊

**Comment by huangzhhui** [comment]
这是新语法
